project:
  type: website
  output-dir: docs
  preview:
    port: 4202
  render:
    - "*.qmd"
    - "!*.Rmd"

website:
  title: "Data Usage with Postprocessing"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



